### ISSUE TITLE
Getting errors while installing example-extension dependencies

### ISSUE THREAD

**Issue by jasham** [jakubsta/example-extension#1]
Hello Jakubsta,

I am in middle of my project where I have to create chrome-extension.

Basically that chrome extension will takes data from block-chain and display in chrome content-script also when user click on that data one transaction happen which will increase the count in block-chain.
It will be a great help from your side if you solve my issue with installation of dependencies of this project.

Below are the error I am getting when I run npm instal; npm start

```
ERROR in ./node_modules/ethjs-unit/lib/index.js
Module build failed: ReferenceError: Unknown plugin "transform-es3-member-expression-literals" specified in "E:\\adbullah\\example-extension-master\\node_modules\\ethjs-unit\\package.json" at 18, attempted to resolve relative to "E:\\adbullah\\example-extension-master\\node_modules\\ethjs-unit"
    at E:\adbullah\example-extension-master\node_modules\babel-core\lib\transformation\file\options\option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (E:\adbullah\example-extension-master\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (E:\adbullah\example-extension-master\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at OptionManager.init (E:\adbullah\example-extension-master\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (E:\adbullah\example-extension-master\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (E:\adbullah\example-extension-master\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transform (E:\adbullah\example-extension-master\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transpile (E:\adbullah\example-extension-master\node_modules\babel-loader\lib\index.js:50:20)
    at Object.module.exports (E:\adbullah\example-extension-master\node_modules\babel-loader\lib\index.js:173:20)
 @ ./node_modules/Web3/node_modules/web3-utils/src/index.js 25:16-37
 @ ./node_modules/Web3/src/index.js
 @ ./background.js

ERROR in ./background.js
Module not found: Error: Can't resolve 'metamask-extension/app/scripts/lib/inpage-provider' in 'E:\adbullah\example-extension-master'
 @ ./background.js 3:0-88 9:25-47

ERROR in ./background.js
Module not found: Error: Can't resolve 'metamask-extension/app/scripts/lib/port-stream' in 'E:\adbullah\example-extension-master'
 @ ./background.js 4:0-72 8:25-35
```

**Thanks,
Jasham**

**Comment by jakubsta** [comment]
Hi @jasham 
Did you try `yarn install --pure-lockfile`? I've tested it with node v9.3.0 and yarn v1.6.0.
